/*
 * Copyright (C) 2012-2016 NS Solutions Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.22 at 10:29:52 AM JST
//


package com.htmlhifive.sourcebuilder.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for module complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="module">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dependencies" type="{}dependencies"/>
 *         &lt;element name="files" type="{}files"/>
 *         &lt;element name="cssfiles" type="{}files"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="selectable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "module", propOrder = {
		"dependencies",
		"files",
		"cssfiles"
})
public class Module {

	@XmlElement(required = true)
	protected Dependencies dependencies;
	@XmlElement(required = true)
	protected Files files;
	@XmlElement(required = true)
	protected Files cssfiles;
	@XmlAttribute(name = "name", required = true)
	protected String name;
	@XmlAttribute(name = "description", required = true)
	protected String description;
	@XmlAttribute(name = "selectable")
	protected Boolean selectable;

    /**
	 * Gets the value of the dependencies property.
	 *
	 * @return possible object is {@link Dependencies }
	 *
	 */
	public Dependencies getDependencies() {
		return dependencies;
	}

    /**
	 * Sets the value of the dependencies property.
	 *
	 * @param value allowed object is {@link Dependencies }
	 *
	 */
	public void setDependencies(Dependencies value) {
		this.dependencies = value;
	}

    /**
	 * Gets the value of the files property.
	 *
	 * @return possible object is {@link Files }
	 *
	 */
	public Files getFiles() {
		return files;
	}

    /**
	 * Sets the value of the files property.
	 *
	 * @param value allowed object is {@link Files }
	 *
	 */
	public void setFiles(Files value) {
		this.files = value;
	}

    /**
	 * Gets the value of the cssfiles property.
	 *
	 * @return possible object is {@link Files }
	 *
	 */
	public Files getCssfiles() {
		return cssfiles;
	}

    /**
	 * Sets the value of the cssfiles property.
	 *
	 * @param value allowed object is {@link Files }
	 *
	 */
	public void setCssfiles(Files value) {
		this.cssfiles = value;
	}

    /**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return name;
	}

    /**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

    /**
	 * Gets the value of the description property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDescription() {
		return description;
	}

    /**
	 * Sets the value of the description property.
	 *
	 * @param value allowed object is {@link String }
	 *
	 */
	public void setDescription(String value) {
		this.description = value;
	}

    /**
	 * Gets the value of the selectable property.
	 *
	 * @return possible object is {@link Boolean }
	 *
	 */
	public boolean isSelectable() {
		if (selectable == null) {
			return true;
		} else {
			return selectable;
		}
	}

    /**
	 * Sets the value of the selectable property.
	 *
	 * @param value allowed object is {@link Boolean }
	 *
	 */
	public void setSelectable(Boolean value) {
		this.selectable = value;
	}

}
